import { DefaultTheme } from '@react-navigation/native'
import { createTheme } from '@shopify/restyle'
import { palette } from './palette'
import { typography } from './typography'
import { mvs, s, vs } from 'react-native-size-matters/extend'
import { omit } from '@utils/lodash'

export const theme = createTheme({
  navigation: {
    dark: false,
    colors: {
      ...DefaultTheme.colors,
      primary: palette.green,
      background: palette.mercury,
      card: palette.white,
      text: palette.black,
      notification: palette.black,
      border: palette.mercury,
    },
  },
  colors: {
    ...omit(palette, 'gradient'),
    primary: palette.green,
    text: palette.black,
    transparent: 'transparent',
    inputBorder: '#BDBDBD',
    line: palette.shuttleGray,
    label: palette.gray,
  },
  borderRadii: {
    none: 0,
    // will remove soon
    t: s(2),
    xs: s(4),
    xss: s(6),
    s: s(8),
    sl: s(12),
    sm: s(14),
    m: s(16),
    ml: s(18),
    ls: s(20),
    l: s(24),
    xl: s(26),
    h: s(36),

    // refactor
    's-0': 0,
    's-0.5': s(2),
    's-1': s(4),
    's-1.5': s(6),
    's-2': s(8),
    's-2.5': s(10),
    's-3': s(12),
    's-3.5': s(14),
    's-4': s(16),
    's-4.5': s(18),
    's-5': s(20),
    's-6': s(24),
    's-7': s(28),
    's-8': s(32),
    's-9': s(36),
    's-12': s(48),
  },
  spacing: {
    none: 0,
    // will remove soon
    xs: s(4),
    s: s(8),
    sl: s(12),
    sm: s(14),
    m: s(16),
    ml: s(18),
    ls: s(20),
    l: s(24),
    lx: s(26),
    xl: s(30),
    xsl: s(38),
    xxl: s(48),
    h: s(54),
    vsm: vs(14),
    vml: vs(18),
    vxl: vs(30),
    vxsl: vs(38),
    vh: vs(54),
    // refactor
    's-0': 0,
    's-0.5': s(2),
    's-1': s(4),
    's-1.5': s(6),
    's-2': s(8),
    's-2.5': s(10),
    's-3': s(12),
    's-3.5': s(14),
    's-4': s(16),
    's-4.5': s(18),
    's-5': s(20),
    's-6': s(24),
    's-7': s(28),
    's-8': s(32),
    's-9': s(36),
    's-9.5': s(38),
    's-10': s(40),
    's-11': s(44),
    's-12': s(48),
    's-13': s(52),
    's-14': s(56),
    's-15': s(60),
    's-16': s(64),
    'vs-0': 0,
    'vs-0.5': vs(2),
    'vs-1': vs(4),
    'vs-1.5': vs(6),
    'vs-2': vs(8),
    'vs-2.5': vs(10),
    'vs-3': vs(12),
    'vs-3.5': vs(14),
    'vs-4': vs(16),
    'vs-4.5': vs(18),
    'vs-5': vs(20),
    'vs-5.5': vs(22),
    'vs-6': vs(24),
    'vs-6.5': vs(26),
    'vs-7': vs(28),
    'vs-7.5': vs(30),
    'vs-8': vs(32),
    'vs-9': vs(36),
    'vs-10': vs(40),
    'vs-11': vs(44),
    'vs-12': vs(48),
    'vs-13': vs(52),
    'vs-14': vs(56),
    'vs-15': vs(60),
    'vs-16': vs(64),
    'vs-17': vs(68),
    'vs-18': vs(72),
    'vs-19': vs(76),
    'vs-20': vs(80),
  },
  breakpoints: {
    phone: 0,
    tablet: 768,
  },
  textVariants: {
    bold: {
      fontFamily: typography.fontFamily.primary.bold,
      fontSize: typography.fontSize.regular,
      color: 'black',
    },
    regular: {
      fontFamily: typography.fontFamily.primary.regular,
      fontSize: typography.fontSize.regular,
      color: 'black',
    },
    medium: {
      fontFamily: typography.fontFamily.primary.medium,
      fontSize: typography.fontSize.medium,
      color: 'black',
    },
    semiBold: {
      fontFamily: typography.fontFamily.primary.semiBold,
      fontSize: typography.fontSize.regular,
      color: 'black',
    },
    small: {
      fontFamily: typography.fontFamily.primary.regular,
      fontSize: typography.fontSize.small,
      color: 'black',
    },
    tiny: {
      fontFamily: typography.fontFamily.primary.regular,
      fontSize: typography.fontSize.tiny,
      color: 'black',
    },
    button: {
      fontFamily: typography.fontFamily.primary.bold,
      fontSize: typography.fontSize.regular,
      color: 'white',
    },
  },
  buttonVariants: {
    solid: {
      paddingHorizontal: 'sm',
      height: vs(36),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'primary',
      paddingVertical: 0,
    },
    clear: {
      padding: 0,
      backgroundColor: 'transparent',
      height: vs(36),
      alignItems: 'center',
      justifyContent: 'center',
    },
    outline: {
      paddingHorizontal: 'sm',
      paddingVertical: 0,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderColor: 'primary',
      borderWidth: s(0.5),
      height: vs(36),
    },
  },
  inputVariants: {
    default: {
      backgroundColor: 'white',
    },
    rounded: {
      borderRadius: 'xss',
      backgroundColor: 'white',
    },
    none: {
      borderBottomWidth: 0,
    },
  },
})

export type Theme = typeof theme

export const darkTheme: Theme = {
  ...theme,
}
