const Routes = {
  Main: <const>'Main',
  Welcome: <const>'Welcome',
  Splash: <const>'Splash',
  NotificationPrompt: <const>'NotificationPrompt',
  AthleteNavigator: <const>'AthleteNavigator',
  Athlete: {
    Dashboard: <const>'Athlete/Dashboard',
    EditProfile: <const>'Athlete/EditProfile',
    UpcomingCall: <const>'Athlete/UpcomingCall',
    Completed: <const>'Athlete/Completed',
    Invite: <const>'Athlete/Invite',
    VideoCall: <const>'Athlete/VideoCall',
    Block: <const>'Athlete/Block',
    VideoCallFeedback: <const>'Athlete/VideoCallFeedback',
    QuickAccess: <const>'Athlete/QuickAccess',
    SignUp: <const>'Athlete/SignUp',
    EnterProcode: <const>'Athlete/EnterProcode',
    SignIn: <const>'Athlete/SignIn',
    AccountPendingApproval: <const>'Athlete/AccountPendingApproval',
    ApplyProCode: <const>'Athlete/ApplyProCode',
    ResetPassword: <const>'Athlete/ResetPassword',
    ChangePassword: <const>'Athlete/ChangePassword',
    EnterEmail: <const>'Athlete/EnterEmail',
    Onboarding: <const>'Athlete/Onboarding',
    PersonalInformation: <const>'Athlete/PersonalInformation',
    SocialMedia: <const>'Athlete/SocialMedia',
    CallRate: <const>'Athlete/CallRate',
    TakePicture: <const>'Athlete/TakePicture',
    SignUpCompleted: <const>'Athelete/SignUpCompleted'
  },
  FanNavigator: <const>'FanNavigator',
  Fan: {
    Dashboard: <const>'Fan/Dashboard',
    Completed: <const>'Fan/Completed',
    Talent: <const>'Fan/Talent',
    VideoCall: <const>'Fan/VideoCall',
    Block: <const>'Fan/Block',
    SignIn: <const>'Fan/SignIn',
    SignUp: <const>'Fan/SignUp',
    EditProfile: <const>'Fan/EditProfile',
    TalentDetail: <const>'Fan/TalentDetail',
    TalentNavigator: <const>'Fan/TalentNavigator',
    ThankYouSignUp: <const>'Fan/ThankYouSignUp',
    Booking: <const>'Fan/Booking',
    BookingSuccess: <const>'Fan/BookingSuccess',
    SearchTalent: <const>'Fan/SearchTalent',
    FanWaitList: <const>'Fan/FanWaitList',
    PostFanWaitList: <const>'Fan/PostFanWaitList',
    FanInviteFriends: <const>'Fan/FanInviteFriends',
  },
}

export default Routes
